### ISSUE TITLE
Break out monolithic elephantdb jar

### ISSUE THREAD

**Issue by sorenmacbeth** [nathanmarz/elephantdb#10]
Having the server, hadoop, and client code all in a single jar is causing problem with depedency on cascading-kryo in the server component when it probably shouldn't use that. 

Perhaps we should break out into separate jars:

elephantdb-core (or common)
elephantdb-server
elephantdb-hadoop
elephantdb-client
elephantdb-ui

Creating this issue as a place to discuss and share ideas.

**Comment by sorenmacbeth** [comment]
We'll do this using lein-sub

**Comment by sritchie** [comment]
Boom, #17
