### ISSUE TITLE
elephantdb/elephantdb-server 0.4.4 available, but no elephantdb 0.4.4

### ISSUE THREAD

**Issue by jeroenvandijk** [nathanmarz/elephantdb#21]
There is no mother project version for Elephantdb 0.4.4, but there is one for all of the sub-projects. Is this on purpose?

See https://clojars.org/elephantdb

And https://clojars.org/elephantdb/elephantdb-server

**Comment by sorenmacbeth** [comment]
I fixed this. It should be available now.
