### ISSUE TITLE
oracle repository corrupts build

### ISSUE THREAD

**Issue by jblomo** [nathanmarz/elephantdb#3]
This may not be an elephantdb bug per se, but it can be resolved by removing the repositories line in `project.clj`:

```
  :repositories {"oracle" "http://download.oracle.com/maven"}
```

The symptom occurs when building elephantdb from the current snapshot.  `lein` downloads dependencies, and hits the oracle repository first.  Instead of returning a 404 for artifacts it doesn't have, it sends back HTML which corrupts the maven archive.  But the Oracle archive doesn't even appear to be necessary to build the project.

**Comment by nathanmarz** [comment]
It's indeed broken, but when I remove the repository it can't find BDB JE. Do you know where the repository hosting that artifact is?

**Comment by jblomo** [comment]
Oh, maven must have correctly grabbed the jar before I removed the line from project.clj.  I couldn't find any options to specify a repository for only one dependency, nor could I find a way to specify repository ordering.  Unfortunately, I can't reproduce the bug now (perhaps Oracle fixed the issue?), but two workarounds: 1) have a clojars placeholder dependency whose only dependency is jde from oracle, 2) set `:always {:checksum :fail}` in the repository spec.

Or you can close this bug as an upstream (maven) problem.

**Comment by nathanmarz** [comment]
Indeed, looks like it was a temporary problem with Oracle's Maven repo.
